[platformio]
default_envs = trgb_full_circle
boards_dir = boards

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default_16MB.csv
board_build.arduino.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
lib_ldf_mode = deep+
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=1
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DLV_CONF_SUPPRESS_DEFINE_CHECK
    -I$PROJECT_INCLUDE_DIR
    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/FS/src
    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Network/src
    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/SPI/src
monitor_filters =
    esp32_exception_decoder
    time

[env:trgb_full_circle]
board = trgb_full_circle
build_flags =
    ${env.build_flags}
    -DHOMESMTHNG_BOARD_TRGB_FULL_CIRCLE
lib_deps =
    homespan/HomeSpan @ ^2.1.6
    https://github.com/Xinyuan-LilyGO/LilyGo-T-RGB.git#359c03f7cd8e9aaadd4bf0f3fbf790844fd95f98
    https://github.com/moononournation/Arduino_GFX.git#1b8df811bc3db8e3fe39c1699676f9ba8d4b8f31

[env:lilygo_amoled_175]
board = lilygo_amoled_175
build_flags =
    ${env.build_flags}
    -DHOMESMTHNG_BOARD_LILYGO_AMOLED_175
lib_deps =
    homespan/HomeSpan @ ^2.1.6
    lvgl/lvgl @ 8.4.0
    lewisxhe/SensorLib @ 0.2.4
    https://github.com/moononournation/Arduino_GFX.git#1b8df811bc3db8e3fe39c1699676f9ba8d4b8f31

[env:waveshare_amoled_175]
board = waveshare_amoled_175
build_flags =
    ${env.build_flags}
    -DHOMESMTHNG_BOARD_WAVESHARE_AMOLED_175
lib_deps =
    homespan/HomeSpan @ ^2.1.6
    lvgl/lvgl @ 8.4.0
    lewisxhe/SensorLib @ 0.2.4
    https://github.com/moononournation/Arduino_GFX.git#1b8df811bc3db8e3fe39c1699676f9ba8d4b8f31
